# @package _global_

defaults:
  - _self_
  - data: cifar10.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: cifar10.yaml
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: checkpoints/epoch_000.ckpt
